services:
  postgres:
    image: postgres:16
    container_name: job-tracker-postgres
    environment:
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - job-tracker-pg:/var/lib/postgresql/data

volumes:
  job-tracker-pg:
